INSERT INTO olympics.sport(sport_name,sport_id) VALUES
('Fencing',1),
('Football',2),
('Athletics',3),
('Equestrian',4),
('Diving',5),
('Canoe Sprint',6),
('Shooting',7),
('Weightlifting',8),
('Boxing',9),
('Rowing',10),
('Archery',11),
('Wrestling',12),
('Cycling',13),
('Judo',14),
('Gymnastics - Artistic',15),
('Taekwondo',16),
('Swimming',17),
('Water Polo',18),
('Beach Volleyball',19),
('Triathlon',20),
('Sailing',21),
('Synchronised Swimming',22),
('Tennis',23),
('Badminton',24),
('Trampoline',25),
('Canoe Slalom',26),
('Table Tennis',27),
('BMX',28);